"""
Part 4: Customization, Annotations & Publication Export
PyMastery Progressive Matplotlib Curriculum
"""

import matplotlib
matplotlib.use("Agg")  # Non-interactive headless backend for server execution
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.text as mtext
import numpy as np
import io
from typing import Dict, Any, List, Tuple, Optional, Union

DAY_METADATA = {
    "day_id": "mpl_part04",
    "part_number": 4,
    "day_number": 4,
    "title": "Part 4: Customization, Annotations & Export",
    "tagline": "Master arrow annotations, spines cleanup, styling sheets, and publication-ready exports.",
    "estimated_time": "1-2 hours",
    "concepts_covered": [
        "Callout annotations with ax.annotate() and arrowprops",
        "Spines minimalism (hiding top and right boundary lines)",
        "Tick customization (tick_params, direction, length, rotation)",
        "Scoped theming with plt.style.context()",
        "Publication-ready export to high-resolution PNG and vector SVG formats"
    ]
}

CONCEPT_PRIMER = r"""# Part 4 Concept Primer: Customization, Annotations & Publication Export

## 1. Pinpoint Annotations with Arrows (`ax.annotate`)
In research and production reporting, raw charts are insufficient—stakeholders need direct visual guidance to understand critical events, peak anomalies, or phase transitions.

While `ax.text(x, y, "label")` places text at a coordinate, `ax.annotate()` separates the **target point** being pointed at (`xy`) from the **text location** (`xytext`), connected by a configurable arrow (`arrowprops`):

```python
ax.annotate(
    text="Flash Crash (-14%)",
    xy=(anomaly_x, anomaly_y),          # Coordinate of data point to point to
    xytext=(anomaly_x + 2, anomaly_y + 10), # Coordinate where text box sits
    arrowprops=dict(
        facecolor="#dc2626",
        edgecolor="#dc2626",
        arrowstyle="->",
        lw=1.8
    ),
    fontsize=10,
    fontweight="bold",
    color="#dc2626"
)
```

---

## 2. Spines & Ticks: The Tufte Minimalist Standard
Edward Tufte's principle of "data-ink ratio" teaches us that every pixel on a chart should communicate data. Standard Matplotlib charts enclose plots in a heavy 4-sided box (spines). Top and right spines rarely serve any purpose and add visual clutter.

### Despining the Figure:
```python
# Hide top and right spines
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

# Emphasize bottom and left axes
ax.spines["left"].set_linewidth(1.2)
ax.spines["bottom"].set_linewidth(1.2)
```

### Refining Ticks:
```python
ax.tick_params(
    axis="both",
    direction="out",     # Ticks point outwards
    length=5,
    width=1.2,
    labelsize=10
)
```

---

## 3. Scoped Theming: `plt.style.context()`
Avoid calling `plt.style.use('seaborn-v0_8')` globally in server environments or libraries because it mutates global configuration (`matplotlib.rcParams`), corrupting plots generated by concurrent tasks.

Instead, use context managers:
```python
with plt.style.context("seaborn-v0_8-whitegrid"):
    fig, ax = plt.subplots()
    ax.plot(x, y)
```

---

## 4. Exporting High-Resolution & Vector Figures
When exporting figures for academic papers, PDFs, or web frontends:

1. **Raster Formats (PNG):**
   - High print resolution requires `dpi=300` or higher.
   - Always pass `bbox_inches='tight'` to prevent labels on figure edges from being cut off.
2. **Vector Formats (SVG / PDF):**
   - SVGs store shapes mathematically, allowing infinite zooming without pixelation in web browsers.

### Safe In-Memory Server Rendering:
```python
buf = io.BytesIO()
fig.savefig(buf, format="png", dpi=300, bbox_inches="tight")
buf.seek(0)
png_bytes = buf.getvalue()
```
"""

WALKTHROUGH = r"""# Part 4 Code Walkthrough: Annotation & Publication Polish

Here is how you detect a signal anomaly, highlight it with an arrow callout, clean spines, and export to in-memory bytes:

```python
import matplotlib
matplotlib.use("Agg")
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.text as mtext
import numpy as np
import io

# 1. Generate signal with an engineered anomaly spike
t = np.linspace(0, 10, 100)
signal = np.sin(t) + 0.1 * np.random.randn(100)
signal[65] += 2.8  # Inject spike anomaly

# 2. Locate peak anomaly
mean_val = np.mean(signal)
peak_idx = int(np.argmax(np.abs(signal - mean_val)))
peak_t, peak_y = t[peak_idx], signal[peak_idx]

# 3. Create styled figure
fig, ax = plt.subplots(figsize=(8, 4.5), dpi=150)
ax.plot(t, signal, color="#2563eb", linewidth=1.8, label="Sensor Telemetry")
ax.scatter(peak_t, peak_y, color="#dc2626", s=80, zorder=5, label="Anomaly")

# 4. Add arrow annotation
ax.annotate(
    f"Peak Anomaly: {peak_y:.2f}",
    xy=(peak_t, peak_y),
    xytext=(peak_t + 0.8, peak_y + 0.5),
    arrowprops=dict(facecolor="#dc2626", edgecolor="#dc2626", arrowstyle="->", lw=1.5),
    fontweight="bold",
    fontsize=9
)

# 5. Clean spines & ticks
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.tick_params(direction="out", length=5)

ax.set_title("Real-Time Telemetry Anomaly Detection", fontweight="bold")
ax.set_xlabel("Time (s)")
ax.set_ylabel("Voltage (V)")
ax.legend(frameon=False)
fig.tight_layout()

# 6. Export to in-memory PNG
buf = io.BytesIO()
fig.savefig(buf, format="png", dpi=150, bbox_inches="tight")
buf.seek(0)
artifact_bytes = buf.getvalue()
```
"""

# -----------------------------------------------------------------------------
# Challenge 1: Anomaly Annotation & Arrow Highlighter
# -----------------------------------------------------------------------------

CHALLENGE_1 = {
    "id": "mpl-p4-c1",
    "title": "Anomaly Annotation & Arrow Highlighter",
    "difficulty": "Intermediate",
    "category": "Customization & Annotations",
    "description": (
        "Automatically detect the maximum absolute deviation anomaly in a signal series. "
        "Plot the signal, mark the anomaly point with a distinct scatter marker, and attach an arrow "
        "annotation pointing directly at the peak coordinate with custom descriptive text."
    ),
    "instructions": (
        "Write a function `annotate_peak_anomaly(timestamps: np.ndarray, signal: np.ndarray, label_text: str = \"Peak Anomaly\") -> tuple[plt.Figure, plt.Axes]` that:\n"
        "1. Validates inputs:\n"
        "   - If `len(timestamps) == 0` or `len(signal) == 0`, raise `ValueError(\"Inputs cannot be empty\")`.\n"
        "   - If `len(timestamps) != len(signal)`, raise `ValueError(\"Timestamps and signal must have identical length\")`.\n"
        "2. Identifies the peak anomaly index as the point with maximum absolute deviation from the mean: `int(np.argmax(np.abs(signal - np.mean(signal))))`.\n"
        "3. Creates `fig, ax = plt.subplots(figsize=(10, 5))`.\n"
        "4. Plots `timestamps` vs `signal` with `color=\"#2563eb\"`, `linewidth=1.8`, and `label=\"Signal\"`.\n"
        "5. Adds a scatter point at the peak coordinate `(peak_x, peak_y)` with `color=\"#dc2626\"`, `s=80`, `zorder=5`, and `label=\"Anomaly\"`.\n"
        "6. Calls `ax.annotate()` to attach an arrow pointing at `(peak_x, peak_y)` with:\n"
        "   - `text=f\"{label_text}: {peak_y:.2f}\"`\n"
        "   - `xy=(peak_x, peak_y)`\n"
        "   - `xytext=(peak_x + (timestamps.max() - timestamps.min()) * 0.08, peak_y + (signal.max() - signal.min()) * 0.15)`\n"
        "   - `arrowprops=dict(arrowstyle=\"->\", color=\"#dc2626\", lw=1.8)`\n"
        "   - `fontweight=\"bold\"`\n"
        "7. Sets title to `\"Signal Anomaly Detection\"`, x-label to `\"Time (s)\"`, y-label to `\"Amplitude\"`.\n"
        "8. Enables grid and legend, then returns `(fig, ax)`."
    ),
    "starter_code": r'''import matplotlib.pyplot as plt
import numpy as np
from typing import Tuple, Any

def annotate_peak_anomaly(
    timestamps: np.ndarray,
    signal: np.ndarray,
    label_text: str = "Peak Anomaly"
) -> Tuple[plt.Figure, plt.Axes]:
    """
    Detect peak anomaly and attach arrow annotation with callout text.
    
    Returns:
        (fig, ax) tuple
    """
    # TODO: Validate inputs, find anomaly peak, plot signal and scatter, annotate with arrow, return (fig, ax)
    pass
''',
    "reference_solution": r'''import matplotlib.pyplot as plt
import numpy as np
from typing import Tuple

def annotate_peak_anomaly(
    timestamps: np.ndarray,
    signal: np.ndarray,
    label_text: str = "Peak Anomaly"
) -> Tuple[plt.Figure, plt.Axes]:
    """
    Detect peak anomaly and attach arrow annotation with callout text.
    """
    t = np.asarray(timestamps, dtype=float)
    s = np.asarray(signal, dtype=float)
    
    if len(t) == 0 or len(s) == 0:
        raise ValueError("Inputs cannot be empty")
    if len(t) != len(s):
        raise ValueError("Timestamps and signal must have identical length")
        
    mean_val = float(np.mean(s))
    peak_idx = int(np.argmax(np.abs(s - mean_val)))
    peak_x, peak_y = float(t[peak_idx]), float(s[peak_idx])
    
    fig, ax = plt.subplots(figsize=(10, 5))
    
    # Main signal line
    ax.plot(t, s, color="#2563eb", linewidth=1.8, label="Signal")
    
    # Highlight anomaly scatter point
    ax.scatter(peak_x, peak_y, color="#dc2626", s=80, zorder=5, label="Anomaly")
    
    # Offset calculation
    x_span = float(t.max() - t.min()) if (t.max() - t.min()) > 0 else 1.0
    y_span = float(s.max() - s.min()) if (s.max() - s.min()) > 0 else 1.0
    
    ax.annotate(
        text=f"{label_text}: {peak_y:.2f}",
        xy=(peak_x, peak_y),
        xytext=(peak_x + x_span * 0.08, peak_y + y_span * 0.15),
        arrowprops=dict(arrowstyle="->", color="#dc2626", lw=1.8),
        fontweight="bold"
    )
    
    ax.set_title("Signal Anomaly Detection")
    ax.set_xlabel("Time (s)")
    ax.set_ylabel("Amplitude")
    ax.grid(True, linestyle=":", alpha=0.5)
    ax.legend(loc="upper right")
    
    return fig, ax
''',
    "test_suite": r'''import matplotlib
import matplotlib.pyplot as plt
import matplotlib.text as mtext
import numpy as np
import io

def run_tests(candidate_func):
    """
    Automated test harness for Anomaly Annotation & Arrow Highlighter (mpl-p4-c1).
    """
    report = {"passed": True, "tests_run": 0, "errors": []}
    
    def assert_test(condition, msg):
        report["tests_run"] += 1
        if not condition:
            report["passed"] = False
            report["errors"].append(msg)
            raise AssertionError(msg)

    # Test 1: Signal with clear outlier spike
    t = np.linspace(0, 10, 50)
    sig = np.sin(t)
    sig[25] = 5.0  # Dominant peak
    
    result = candidate_func(t, sig, label_text="Spike Error")
    if isinstance(result, tuple) and len(result) == 2:
        fig, ax = result
    elif isinstance(result, plt.Figure):
        fig = result
        ax = fig.axes[0]
    else:
        assert_test(False, f"Expected (fig, ax), got {type(result)}")
        return report

    assert_test(isinstance(fig, plt.Figure), "First returned item must be Figure")
    assert_test(isinstance(ax, plt.Axes), "Second returned item must be Axes")
    
    # Check signal line
    assert_test(len(ax.get_lines()) >= 1, "Must contain Line2D artist for signal")
    
    # Check scatter point for anomaly
    assert_test(len(ax.collections) >= 1, "Must contain scatter point for anomaly")
    scatter_pt = ax.collections[0].get_offsets()
    assert_test(np.allclose(scatter_pt[0], [t[25], 5.0]), f"Anomaly scatter not at peak: expected [{t[25]}, 5.0], got {scatter_pt[0]}")
    
    # Check annotation artist
    annotations = [child for child in ax.get_children() if isinstance(child, matplotlib.text.Annotation)]
    assert_test(len(annotations) >= 1, "Must contain matplotlib.text.Annotation artist")
    
    ann = annotations[0]
    assert_test("spike error" in ann.get_text().lower(), f"Annotation text should contain label_text, got '{ann.get_text()}'")
    assert_test(np.allclose(ann.xy, [t[25], 5.0]), f"Annotation arrow must point to peak coordinate ({t[25]}, 5.0), got {ann.xy}")
    assert_test(ann.arrow_patch is not None, "Annotation must include arrowprops / arrow_patch")
    
    # Check rendering
    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    assert_test(buf.tell() > 1000, "Figure rendering failed")
    plt.close(fig)

    # Test 2: Validation on mismatched lengths
    raised_mismatch = False
    try:
        candidate_func(t[:10], sig)
    except ValueError:
        raised_mismatch = True
    assert_test(raised_mismatch, "Expected ValueError on length mismatch")

    # Test 3: Validation on empty inputs
    raised_empty = False
    try:
        candidate_func(np.array([]), np.array([]))
    except ValueError:
        raised_empty = True
    assert_test(raised_empty, "Expected ValueError on empty inputs")

    return report
''',
    "hints": [
        "Use `np.argmax(np.abs(signal - np.mean(signal)))` to detect the peak anomaly index.",
        "Use `ax.annotate(text, xy=(peak_x, peak_y), xytext=..., arrowprops=dict(arrowstyle='->', ...))`.",
        "Make sure to scatter mark the anomaly point with `ax.scatter(peak_x, peak_y)`."
    ]
}

# -----------------------------------------------------------------------------
# Challenge 2: Publication-Ready Scientific Figure
# -----------------------------------------------------------------------------

CHALLENGE_2 = {
    "id": "mpl-p4-c2",
    "title": "Publication-Ready Scientific Figure",
    "difficulty": "Advanced",
    "category": "Customization & Export",
    "description": (
        "Build a publication-grade scientific figure with error bars, Tufte minimalist spines "
        "(hidden top and right boundary lines, thickened data axes), outward tick parameters, "
        "and in-memory buffer export to high-resolution PNG or vector SVG format."
    ),
    "instructions": (
        "Write a function `build_publication_figure(x: np.ndarray, y: np.ndarray, y_err: np.ndarray, export_format: str = \"png\", dpi: int = 300) -> tuple[plt.Figure, bytes]` that:\n"
        "1. Validates inputs:\n"
        "   - If `export_format.lower()` is not in `(\"png\", \"svg\", \"pdf\")`, raise `ValueError(\"Unsupported export format\")`.\n"
        "   - If `len(x) == 0`, `len(y) == 0`, or `len(y_err) == 0`, raise `ValueError(\"Inputs cannot be empty\")`.\n"
        "   - If `len(x) != len(y)` or `len(x) != len(y_err)`, raise `ValueError(\"Array lengths must match\")`.\n"
        "   - If `dpi < 72`, raise `ValueError(\"DPI must be at least 72\")`.\n"
        "2. Creates `fig, ax = plt.subplots(figsize=(7, 4.5), dpi=dpi)`.\n"
        "3. Plots `ax.errorbar(x, y, yerr=y_err, fmt=\"-o\", color=\"#0f172a\", ecolor=\"#64748b\", elinewidth=1.5, capsize=4, capthick=1.5, markersize=5, label=\"Measurements\")`.\n"
        "4. Cleans up spines:\n"
        "   - Hides top spine (`ax.spines[\"top\"].set_visible(False)`)\n"
        "   - Hides right spine (`ax.spines[\"right\"].set_visible(False)`)\n"
        "   - Sets left spine linewidth to 1.2 (`ax.spines[\"left\"].set_linewidth(1.2)`)\n"
        "   - Sets bottom spine linewidth to 1.2 (`ax.spines[\"bottom\"].set_linewidth(1.2)`)\n"
        "5. Configures ticks: `ax.tick_params(direction=\"out\", length=5, width=1.2)`.\n"
        "6. Sets title to `\"Experimental Response Function\"`, x-label to `\"Independent Variable (X)\"`, y-label to `\"Response (Y)\"`.\n"
        "7. Adds a borderless legend (`ax.legend(frameon=False)`).\n"
        "8. Calls `fig.tight_layout()`.\n"
        "9. Saves figure to an in-memory `io.BytesIO` buffer with `fig.savefig(buf, format=export_format.lower(), dpi=dpi, bbox_inches=\"tight\")`.\n"
        "10. Returns `(fig, buf.getvalue())`."
    ),
    "starter_code": r'''import matplotlib.pyplot as plt
import numpy as np
from typing import Tuple, Any

def build_publication_figure(
    x: np.ndarray,
    y: np.ndarray,
    y_err: np.ndarray,
    export_format: str = "png",
    dpi: int = 300
) -> Tuple[plt.Figure, bytes]:
    """
    Construct a publication-ready figure with error bars, despined axes, and in-memory export.
    
    Returns:
        (fig, image_bytes)
    """
    # TODO: Validate format/inputs, plot errorbars, despine top/right, export to BytesIO, return (fig, bytes)
    pass
''',
    "reference_solution": r'''import matplotlib
import matplotlib.pyplot as plt
import matplotlib.text as mtext
import numpy as np
import io
from typing import Tuple

def build_publication_figure(
    x: np.ndarray,
    y: np.ndarray,
    y_err: np.ndarray,
    export_format: str = "png",
    dpi: int = 300
) -> Tuple[plt.Figure, bytes]:
    """
    Construct a publication-ready figure with error bars, despined axes, and in-memory export.
    """
    fmt = export_format.lower().strip()
    if fmt not in ("png", "svg", "pdf"):
        raise ValueError(f"Unsupported export format: {export_format}")
    if len(x) == 0 or len(y) == 0 or len(y_err) == 0:
        raise ValueError("Inputs cannot be empty")
    if len(x) != len(y) or len(x) != len(y_err):
        raise ValueError("Array lengths must match")
    if dpi < 72:
        raise ValueError("DPI must be at least 72")
        
    fig, ax = plt.subplots(figsize=(7, 4.5), dpi=dpi)
    
    ax.errorbar(
        x, y, yerr=y_err,
        fmt="-o",
        color="#0f172a",
        ecolor="#64748b",
        elinewidth=1.5,
        capsize=4,
        capthick=1.5,
        markersize=5,
        label="Measurements"
    )
    
    # Despine top and right
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.spines["left"].set_linewidth(1.2)
    ax.spines["bottom"].set_linewidth(1.2)
    
    ax.tick_params(direction="out", length=5, width=1.2)
    
    ax.set_title("Experimental Response Function")
    ax.set_xlabel("Independent Variable (X)")
    ax.set_ylabel("Response (Y)")
    ax.legend(frameon=False)
    
    fig.tight_layout()
    
    buf = io.BytesIO()
    fig.savefig(buf, format=fmt, dpi=dpi, bbox_inches="tight")
    buf.seek(0)
    image_bytes = buf.getvalue()
    
    return fig, image_bytes
''',
    "test_suite": r'''import matplotlib
import matplotlib.pyplot as plt
import matplotlib.text as mtext
import numpy as np
import io

def run_tests(candidate_func):
    """
    Automated test harness for Publication-Ready Scientific Figure (mpl-p4-c2).
    """
    report = {"passed": True, "tests_run": 0, "errors": []}
    
    def assert_test(condition, msg):
        report["tests_run"] += 1
        if not condition:
            report["passed"] = False
            report["errors"].append(msg)
            raise AssertionError(msg)

    # Test 1: Standard publication figure export (PNG)
    x = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
    y = np.array([2.1, 4.3, 6.0, 8.2, 10.5])
    y_err = np.array([0.2, 0.3, 0.25, 0.4, 0.35])
    
    result = candidate_func(x, y, y_err, export_format="png", dpi=150)
    assert_test(isinstance(result, tuple) and len(result) == 2, "Expected (fig, bytes) tuple")
    fig, img_bytes = result
    
    assert_test(isinstance(fig, plt.Figure), "First returned element must be Figure")
    assert_test(isinstance(img_bytes, bytes), "Second returned element must be bytes")
    assert_test(len(img_bytes) > 5000, f"Exported PNG byte buffer too small: {len(img_bytes)} bytes")
    
    ax = fig.axes[0]
    
    # Check despined top and right
    assert_test(not ax.spines["top"].get_visible(), "Top spine must be invisible")
    assert_test(not ax.spines["right"].get_visible(), "Right spine must be invisible")
    
    # Check errorbar container
    assert_test(len(ax.containers) >= 1 or len(ax.lines) >= 1, "Must contain errorbar container or lines")
    
    # Check labels
    assert_test("response" in ax.get_title().lower() or "experimental" in ax.get_title().lower(), "Title must mention Response/Experimental")
    assert_test(len(ax.get_xlabel().strip()) > 0, "X-label cannot be empty")
    assert_test(len(ax.get_ylabel().strip()) > 0, "Y-label cannot be empty")
    
    plt.close(fig)

    # Test 2: SVG export
    fig_svg, svg_bytes = candidate_func(x, y, y_err, export_format="svg")
    assert_test(b"<svg" in svg_bytes, "Exported SVG bytes must contain '<svg' tag")
    plt.close(fig_svg)

    # Test 3: Validation on unsupported format
    raised_fmt = False
    try:
        candidate_func(x, y, y_err, export_format="bmp")
    except ValueError:
        raised_fmt = True
    assert_test(raised_fmt, "Expected ValueError on unsupported format 'bmp'")

    # Test 4: Validation on invalid DPI (< 72)
    raised_dpi = False
    try:
        candidate_func(x, y, y_err, dpi=50)
    except ValueError:
        raised_dpi = True
    assert_test(raised_dpi, "Expected ValueError when dpi < 72")

    return report
''',
    "hints": [
        "Use `ax.errorbar(x, y, yerr=y_err, fmt='-o', capsize=4)` to plot error bars.",
        "To despine: `ax.spines['top'].set_visible(False)` and `ax.spines['right'].set_visible(False)`.",
        "Save into `io.BytesIO()` using `fig.savefig(buf, format=export_format, dpi=dpi, bbox_inches='tight')` and return `buf.getvalue()`."
    ]
}

CHALLENGES = [CHALLENGE_1, CHALLENGE_2]

CURRICULUM_DATA = {
    **DAY_METADATA,
    "concept_primer": CONCEPT_PRIMER,
    "walkthrough": WALKTHROUGH,
    "challenges": CHALLENGES
}

def get_curriculum() -> Dict[str, Any]:
    return CURRICULUM_DATA
