"""
Part 5: Merging, Joining & Combining Tables
PyMastery Progressive Pandas Curriculum
"""

import pandas as pd
import numpy as np
from typing import Dict, Any, List

DAY_METADATA = {
    "day_id": "pandas_day05",
    "day_number": 5,
    "title": "Part 5: Merging, Joining & Combining Tables",
    "tagline": "Connect the dots across tables: master pd.concat for stacking and pd.merge for SQL-style relational joins.",
    "estimated_time": "2-3 hours",
    "concepts_covered": [
        "Concatenating tables with pd.concat (row stacking vs column stacking)",
        "Database-style joins with pd.merge (inner, left, right, outer)",
        "Join key selection (on, left_on, right_on, left_index, right_index)",
        "Handling overlapping column names with suffixes",
        "Addressing missing data (NaN) generated by non-matching joins",
        "Validating merge integrity (validate='one_to_many', etc.)"
    ]
}

CONCEPT_PRIMER = r"""# Part 5 Concept Primer: Merging, Joining & Combining Tables

## 1. Why Do We Need Multiple Tables?
In the real world, data rarely lives in a single, monolithic spreadsheet:
- **Relational Databases (SQL):** Systems store customers in one table, orders in another, and product catalogs in a third to avoid duplicating information (database normalization).
- **Periodic Logs:** Sales or telemetry logs are frequently generated in separate files per day, month, or quarter (`sales_q1.csv`, `sales_q2.csv`).
- **Multi-Source Analytics:** Merging internal company CRM data with external market indices or geographic coordinates.

To analyze this data, you must know how to combine tables cleanly and efficiently. Pandas provides two primary tools:
1. **`pd.concat()`**: Stacking or gluing DataFrames together along an axis (rows or columns).
2. **`pd.merge()`**: Performing relational database-style joins using shared key columns.

---

## 2. Stacking Data: `pd.concat`

Think of `pd.concat()` like stacking physical sheets of paper:
- **`axis=0` (Vertical Stacking - Default):** Gluing rows together. Great for appending monthly logs with the same columns.
- **`axis=1` (Horizontal Stacking):** Gluing columns side-by-side.

```
       Table A                  Table B               pd.concat([A, B], axis=0)
+----+-------+-------+   +----+-------+-------+     +----+-------+-------+
|    | month | sales |   |    | month | sales |     | 0  | Jan   | 100   |
+----+-------+-------+   +----+-------+-------+     | 1  | Feb   | 120   |
| 0  | Jan   | 100   |   | 0  | Mar   | 140   | ==> | 0  | Mar   | 140   |
| 1  | Feb   | 120   |   | 1  | Apr   | 160   |     | 1  | Apr   | 160   |
+----+-------+-------+   +----+-------+-------+     +----+-------+-------+
                                                     Notice index repeated!
```

### The `ignore_index=True` Essential
When you concatenate tables with `axis=0`, Pandas preserves each table's original index by default (leading to duplicate indices like `0, 1, 0, 1`). 
In 95% of cases, you want a fresh, sequential index:
```python
combined = pd.concat([df_q1, df_q2], ignore_index=True)
```

---

## 3. Relational Joins: `pd.merge`

`pd.merge()` is Pandas' implementation of the SQL `JOIN` or Excel `VLOOKUP`. It matches rows from two DataFrames based on one or more common key columns.

```python
merged_df = pd.merge(left_df, right_df, on='customer_id', how='inner')
```

### The Four Join Types (`how=...`)

```
      LEFT TABLE (Customers)               RIGHT TABLE (Orders)
+-------------+----------------+     +----------+-------------+--------+
| customer_id | name           |     | order_id | customer_id | amount |
+-------------+----------------+     +----------+-------------+--------+
| 101         | Alice          |     | 1        | 101         | $50    |
| 102         | Bob            |     | 2        | 101         | $80    |
| 103         | Charlie        |     | 3        | 102         | $120   |
| 104         | Diana (no ord) |     | 4        | 999 (guest) | $40    |
+-------------+----------------+     +----------+-------------+--------+
```

1. **`how='inner'` (Default):**
   Only keeps rows where the key exists in **both** tables.
   - Customers 101 and 102 are kept.
   - Diana (104) is dropped (no orders). Order 4 (999) is dropped (no customer record).

2. **`how='left'`:**
   Keeps **all** rows from the left table. If no match exists in the right table, columns are filled with `NaN`.
   - Diana (104) is kept with `order_id=NaN`, `amount=NaN`.
   - Crucial for retaining all registered customers or all audit events.

3. **`how='right'`:**
   Keeps **all** rows from the right table. (Less common; equivalent to swapping tables in a left join).

4. **`how='outer'` (Full Outer Join):**
   Keeps **all** rows from both tables. Unmatched rows on either side get `NaN`.
   - Perfect for reconciliation audits to find unmatched records in either source.

```
       INNER JOIN                  LEFT JOIN                   OUTER JOIN
+-----+-------+--------+     +-----+-------+--------+     +-----+-------+--------+
| id  | name  | amount |     | id  | name  | amount |     | id  | name  | amount |
+-----+-------+--------+     +-----+-------+--------+     +-----+-------+--------+
| 101 | Alice | 50     |     | 101 | Alice | 50     |     | 101 | Alice | 50     |
| 101 | Alice | 80     |     | 101 | Alice | 80     |     | 101 | Alice | 80     |
| 102 | Bob   | 120    |     | 102 | Bob   | 120    |     | 102 | Bob   | 120    |
+-----+-------+--------+     | 103 | Ch... | NaN    |     | 103 | Ch... | NaN    |
                             | 104 | Diana | NaN    |     | 104 | Diana | NaN    |
                             +-----+-------+--------+     | 999 | NaN   | 40     |
                                                          +-----+-------+--------+
```

---

## 4. Different Key Names & Index Merges

What if the tables call the join column by different names?
- Use `left_on` and `right_on`:
```python
pd.merge(orders, customers, left_on='cust_id', right_on='customer_id', how='left')
```
What if one table has the key in its DataFrame index?
- Use `left_on='customer_id', right_index=True` or `left_index=True, right_index=True`.

---

## 5. Column Collisions: `suffixes`
If both tables share non-key columns with the same name (e.g., `date` or `status`), Pandas adds suffixes to distinguish them:
```python
pd.merge(orders, payments, on='order_id', suffixes=('_order', '_payment'))
# Results in 'date_order' and 'date_payment'
```
"""

WALKTHROUGH = r"""# Part 5 Code Walkthrough: Merging & Combining in Action

Let's test combining and joining datasets using realistic e-commerce and retail tables:

```python
import pandas as pd
import numpy as np

# 1. Customer metadata table
customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4],
    'name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'city': ['New York', 'London', 'Tokyo', 'San Francisco']
})

# 2. Transaction orders table
orders = pd.DataFrame({
    'order_id': [101, 102, 103, 104],
    'customer_id': [1, 2, 1, 99],  # Note: 99 is an unregistered guest
    'amount': [75.50, 120.00, 34.25, 50.00],
    'status': ['completed', 'completed', 'pending', 'completed']
})

print("--- Customers ---")
print(customers)

print("\n--- Orders ---")
print(orders)

# 3. Inner Join: Only customers with orders AND orders with valid customers
inner_result = pd.merge(orders, customers, on='customer_id', how='inner')
print("\n--- Inner Join (Matching records only) ---")
print(inner_result[['order_id', 'customer_id', 'name', 'amount']])

# 4. Left Join: All customers preserved, including those with 0 orders
left_result = pd.merge(customers, orders, on='customer_id', how='left')
# Fill missing amounts for non-purchasing customers
left_result['amount'] = left_result['amount'].fillna(0.0)
print("\n--- Left Join (All customers preserved) ---")
print(left_result[['customer_id', 'name', 'order_id', 'amount']])

# 5. Stacking Quarterly tables with pd.concat
q1 = pd.DataFrame({'quarter': ['Q1', 'Q1'], 'store_id': [10, 20], 'rev': [500, 700]})
q2 = pd.DataFrame({'quarter': ['Q2', 'Q2'], 'store_id': [10, 20], 'rev': [600, 850]})

annual = pd.concat([q1, q2], ignore_index=True)
print("\n--- Vertically Concatenated Tables ---")
print(annual)
```
"""

# -----------------------------------------------------------------------------
# Challenge 1: Customer Order Joiner (pandas-p5-c1)
# -----------------------------------------------------------------------------

CHALLENGE_1 = {
    "id": "pandas-p5-c1",
    "title": "Customer Order Joiner",
    "difficulty": "Beginner",
    "category": "Merging & Joining",
    "description": (
        "Join transactional order records with customer profile metadata using inner and left joins. "
        "Learn how to handle unregistered users, compute per-customer spend metrics with groupby aggregations, "
        "and properly fill missing values for inactive customers."
    ),
    "instructions": (
        "Write a function `join_customer_orders(customers: pd.DataFrame, orders: pd.DataFrame) -> dict` that:\n"
        "1. `inner_merged`: Performs an **inner join** between `orders` and `customers` on `'customer_id'`. "
        "Only orders linked to registered customers should be included.\n"
        "2. `customer_orders_all`: Performs a **left join** starting with `customers` on the left and `orders` on the right "
        "on `'customer_id'`, ensuring every customer is kept. Fill missing values in the `'amount'` column with `0.0`.\n"
        "3. `customer_summary`: Aggregates `customer_orders_all` grouped by `['customer_id', 'name']` to compute:\n"
        "   - `'total_spend'`: sum of `'amount'` (float, rounded to 2 decimal places).\n"
        "   - `'order_count'`: count of valid `'order_id'` entries (customers with no orders must have count `0`).\n"
        "   - `'completed_spend'`: sum of `'amount'` where `'status' == 'completed'` (if no completed orders, `0.0`).\n"
        "   Reset the index so `customer_id` and `name` are columns, and sort ascending by `'customer_id'`.\n"
        "4. Returns a dictionary:\n"
        "   `{\"inner_merged\": inner_merged, \"customer_orders_all\": customer_orders_all, \"customer_summary\": customer_summary}`"
    ),
    "starter_code": r'''import pandas as pd
import numpy as np

def join_customer_orders(customers: pd.DataFrame, orders: pd.DataFrame) -> dict:
    """
    Join customer metadata with orders and compute per-customer spending summaries.

    Args:
        customers: DataFrame with ['customer_id', 'name', 'city', 'signup_date']
        orders: DataFrame with ['order_id', 'customer_id', 'order_date', 'amount', 'status']

    Returns:
        dict with 'inner_merged', 'customer_orders_all', and 'customer_summary'
    """
    # TODO: Implement inner join, left join with fillna, and customer summary aggregation
    pass
''',
    "reference_solution": r'''import pandas as pd
import numpy as np

def join_customer_orders(customers: pd.DataFrame, orders: pd.DataFrame) -> dict:
    # 1. Inner join: orders with valid registered customers
    inner_merged = pd.merge(orders, customers, on="customer_id", how="inner")

    # 2. Left join: all customers, even those without orders
    customer_orders_all = pd.merge(customers, orders, on="customer_id", how="left")
    customer_orders_all["amount"] = customer_orders_all["amount"].fillna(0.0)

    # 3. Customer summary aggregation
    # Helper column for completed spend
    calc_df = customer_orders_all.copy()
    calc_df["completed_amount"] = calc_df["amount"].where(calc_df["status"] == "completed", 0.0)

    customer_summary = calc_df.groupby(["customer_id", "name"], as_index=False).agg(
        total_spend=("amount", "sum"),
        order_count=("order_id", "count"),
        completed_spend=("completed_amount", "sum")
    )
    customer_summary["total_spend"] = customer_summary["total_spend"].round(2)
    customer_summary["completed_spend"] = customer_summary["completed_spend"].round(2)
    customer_summary = customer_summary.sort_values("customer_id").reset_index(drop=True)

    return {
        "inner_merged": inner_merged,
        "customer_orders_all": customer_orders_all,
        "customer_summary": customer_summary,
    }
''',
    "test_suite": r'''import pandas as pd
import numpy as np

def run_tests(candidate_func):
    report = {"passed": True, "tests_run": 0, "errors": []}

    def assert_test(condition, msg):
        report["tests_run"] += 1
        if not condition:
            report["passed"] = False
            report["errors"].append(msg)
            raise AssertionError(msg)

    # Fixtures
    customers_data = pd.DataFrame({
        "customer_id": [1, 2, 3, 4],
        "name": ["Alice", "Bob", "Charlie", "Diana"],
        "city": ["New York", "London", "Tokyo", "Berlin"],
        "signup_date": ["2023-01-10", "2023-03-15", "2023-05-20", "2023-06-01"]
    })

    orders_data = pd.DataFrame({
        "order_id": [101, 102, 103, 104, 105],
        "customer_id": [1, 2, 1, 3, 999],  # 999 is unregistered guest, 4 has no orders
        "order_date": ["2023-07-01", "2023-07-02", "2023-07-03", "2023-07-04", "2023-07-05"],
        "amount": [50.0, 120.5, 30.0, 200.0, 75.0],
        "status": ["completed", "completed", "cancelled", "completed", "completed"]
    })

    res = candidate_func(customers_data, orders_data)
    assert_test(isinstance(res, dict), "Result must be a Python dictionary")
    for key in ["inner_merged", "customer_orders_all", "customer_summary"]:
        assert_test(key in res, f"Dictionary must contain key '{key}'")
        assert_test(isinstance(res[key], pd.DataFrame), f"Value for '{key}' must be a DataFrame")

    inner = res["inner_merged"]
    left = res["customer_orders_all"]
    summary = res["customer_summary"]

    # Test 1: Inner join excludes unregistered customer 999 and customer 4 with no orders
    assert_test(len(inner) == 4, f"inner_merged should have 4 rows, got {len(inner)}")
    assert_test(999 not in inner["customer_id"].values, "Unregistered guest 999 should not appear in inner join")
    assert_test(set(inner["customer_id"].unique()) == {1, 2, 3}, "Inner join customer_ids should be {1, 2, 3}")

    # Test 2: Left join includes all 4 customers
    assert_test(len(left) >= 4, f"customer_orders_all should have at least 4 rows, got {len(left)}")
    assert_test(set(customers_data["customer_id"]).issubset(set(left["customer_id"])), "Left join must keep all customers")
    # Customer 4 amount must be filled with 0.0
    diana_rows = left[left["customer_id"] == 4]
    assert_test(len(diana_rows) == 1, "Customer 4 should appear exactly once in left join")
    assert_test(diana_rows["amount"].iloc[0] == 0.0, f"Customer 4 amount must be filled with 0.0, got {diana_rows['amount'].iloc[0]}")

    # Test 3: Customer summary metrics
    assert_test(len(summary) == 4, f"customer_summary should have 4 rows (1 per customer), got {len(summary)}")
    assert_test(list(summary.columns) == ["customer_id", "name", "total_spend", "order_count", "completed_spend"] or
                set(["customer_id", "name", "total_spend", "order_count", "completed_spend"]).issubset(summary.columns),
                "customer_summary missing required columns")

    c1_summary = summary[summary["customer_id"] == 1].iloc[0]
    assert_test(c1_summary["order_count"] == 2, f"Customer 1 should have 2 orders, got {c1_summary['order_count']}")
    assert_test(np.isclose(c1_summary["total_spend"], 80.0), f"Customer 1 total_spend expected 80.0, got {c1_summary['total_spend']}")
    assert_test(np.isclose(c1_summary["completed_spend"], 50.0), f"Customer 1 completed_spend expected 50.0, got {c1_summary['completed_spend']}")

    c4_summary = summary[summary["customer_id"] == 4].iloc[0]
    assert_test(c4_summary["order_count"] == 0, f"Customer 4 with no orders must have order_count=0, got {c4_summary['order_count']}")
    assert_test(c4_summary["total_spend"] == 0.0, f"Customer 4 total_spend must be 0.0, got {c4_summary['total_spend']}")
    assert_test(c4_summary["completed_spend"] == 0.0, f"Customer 4 completed_spend must be 0.0, got {c4_summary['completed_spend']}")

    # Test 4: Check sorting by customer_id ascending
    assert_test(list(summary["customer_id"]) == [1, 2, 3, 4], "customer_summary must be sorted ascending by customer_id")

    return report
''',
    "hints": [
        "Use pd.merge(orders, customers, on='customer_id', how='inner') for inner join.",
        "Use pd.merge(customers, orders, on='customer_id', how='left') and .fillna({'amount': 0.0}) for left join.",
        "To count orders correctly, aggregate order_id with 'count' (which ignores NaN/null values).",
        "For completed spend, mask or zero-out amounts where status != 'completed' before grouping."
    ]
}

# -----------------------------------------------------------------------------
# Challenge 2: Multi-Source Data Combiner (pandas-p5-c2)
# -----------------------------------------------------------------------------

CHALLENGE_2 = {
    "id": "pandas-p5-c2",
    "title": "Multi-Source Data Combiner",
    "difficulty": "Intermediate",
    "category": "Merging & Joining",
    "description": (
        "Combine distributed quarterly sales tables using pd.concat and enrich them with store location metadata via pd.merge. "
        "Calculate regional performance KPIs including total revenue, unit volume, and store counts."
    ),
    "instructions": (
        "Write a function `combine_retail_data(quarterly_dfs: list, store_locations: pd.DataFrame) -> dict` that:\n"
        "1. `annual_sales`: Vertically concatenates the list of quarterly DataFrames (`quarterly_dfs`) using "
        "`pd.concat(..., ignore_index=True)`.\n"
        "2. `enriched_sales`: Performs a **left join** of `annual_sales` with `store_locations` on `'store_id'` "
        "to append each store's `'city'`, `'region'`, and `'manager'`.\n"
        "3. `region_summary`: Groups `enriched_sales` by `'region'` and calculates:\n"
        "   - `'total_revenue'`: sum of `'revenue'` (float, rounded to 2 decimal places).\n"
        "   - `'total_units'`: sum of `'units_sold'` (int).\n"
        "   - `'avg_quarterly_revenue'`: mean of `'revenue'` (float, rounded to 2 decimal places).\n"
        "   - `'store_count'`: number of distinct stores in the region (`nunique()` on `'store_id'`).\n"
        "   Reset index, and sort descending by `'total_revenue'`.\n"
        "4. Returns a dictionary:\n"
        "   `{\"annual_sales\": annual_sales, \"enriched_sales\": enriched_sales, \"region_summary\": region_summary}`"
    ),
    "starter_code": r'''import pandas as pd
import numpy as np

def combine_retail_data(quarterly_dfs: list, store_locations: pd.DataFrame) -> dict:
    """
    Concatenate quarterly sales records, enrich with location metadata, and summarize by region.

    Args:
        quarterly_dfs: List of DataFrames, each with ['store_id', 'quarter', 'revenue', 'units_sold']
        store_locations: DataFrame with ['store_id', 'city', 'region', 'manager']

    Returns:
        dict with 'annual_sales', 'enriched_sales', and 'region_summary'
    """
    # TODO: Concatenate quarterly DataFrames, merge store locations, and produce regional summary
    pass
''',
    "reference_solution": r'''import pandas as pd
import numpy as np

def combine_retail_data(quarterly_dfs: list, store_locations: pd.DataFrame) -> dict:
    # 1. Concatenate quarterly DataFrames vertically
    annual_sales = pd.concat(quarterly_dfs, ignore_index=True)

    # 2. Enrich with store location metadata via left join
    enriched_sales = pd.merge(annual_sales, store_locations, on="store_id", how="left")

    # 3. Regional summary aggregation
    region_summary = enriched_sales.groupby("region", as_index=False).agg(
        total_revenue=("revenue", "sum"),
        total_units=("units_sold", "sum"),
        avg_quarterly_revenue=("revenue", "mean"),
        store_count=("store_id", "nunique")
    )
    region_summary["total_revenue"] = region_summary["total_revenue"].round(2)
    region_summary["avg_quarterly_revenue"] = region_summary["avg_quarterly_revenue"].round(2)
    region_summary = region_summary.sort_values("total_revenue", ascending=False).reset_index(drop=True)

    return {
        "annual_sales": annual_sales,
        "enriched_sales": enriched_sales,
        "region_summary": region_summary,
    }
''',
    "test_suite": r'''import pandas as pd
import numpy as np

def run_tests(candidate_func):
    report = {"passed": True, "tests_run": 0, "errors": []}

    def assert_test(condition, msg):
        report["tests_run"] += 1
        if not condition:
            report["passed"] = False
            report["errors"].append(msg)
            raise AssertionError(msg)

    # Fixtures
    q1 = pd.DataFrame({
        "store_id": [101, 102, 103],
        "quarter": ["Q1", "Q1", "Q1"],
        "revenue": [15000.0, 22000.0, 18000.0],
        "units_sold": [150, 210, 175]
    })
    q2 = pd.DataFrame({
        "store_id": [101, 102, 103],
        "quarter": ["Q2", "Q2", "Q2"],
        "revenue": [16500.0, 24000.0, 19500.0],
        "units_sold": [160, 230, 190]
    })
    q3 = pd.DataFrame({
        "store_id": [101, 102, 104],
        "quarter": ["Q3", "Q3", "Q3"],
        "revenue": [17000.0, 26000.0, 12000.0],
        "units_sold": [165, 250, 110]
    })

    locations = pd.DataFrame({
        "store_id": [101, 102, 103, 104],
        "city": ["Seattle", "San Francisco", "Austin", "Dallas"],
        "region": ["West", "West", "South", "South"],
        "manager": ["Sarah", "David", "Carlos", "Elena"]
    })

    res = candidate_func([q1, q2, q3], locations)
    assert_test(isinstance(res, dict), "Result must be a Python dictionary")
    for k in ["annual_sales", "enriched_sales", "region_summary"]:
        assert_test(k in res, f"Result missing key '{k}'")
        assert_test(isinstance(res[k], pd.DataFrame), f"Value for '{k}' must be a DataFrame")

    annual = res["annual_sales"]
    enriched = res["enriched_sales"]
    summary = res["region_summary"]

    # Test 1: Stacking check
    assert_test(len(annual) == 9, f"annual_sales must have 9 rows (3 + 3 + 3), got {len(annual)}")
    assert_test(list(annual.index) == list(range(9)), "annual_sales must have a clean RangeIndex (ignore_index=True)")

    # Test 2: Merging check
    assert_test(len(enriched) == 9, f"enriched_sales must have 9 rows, got {len(enriched)}")
    for col in ["city", "region", "manager"]:
        assert_test(col in enriched.columns, f"enriched_sales must have column '{col}'")

    # Test 3: Regional summary aggregations
    assert_test(len(summary) == 2, f"region_summary should have 2 regions ('West', 'South'), got {len(summary)}")
    west_row = summary[summary["region"] == "West"].iloc[0]
    south_row = summary[summary["region"] == "South"].iloc[0]

    # West stores: 101, 102. Q1(15k+22k) + Q2(16.5k+24k) + Q3(17k+26k) = 120,500
    assert_test(np.isclose(west_row["total_revenue"], 120500.0), f"West total_revenue expected 120500.0, got {west_row['total_revenue']}")
    assert_test(west_row["store_count"] == 2, f"West store_count expected 2, got {west_row['store_count']}")
    assert_test(west_row["total_units"] == (150+210 + 160+230 + 165+250), f"West total_units mismatch")

    # South stores: 103, 104. Q1(18k) + Q2(19.5k) + Q3(12k) = 49,500
    assert_test(np.isclose(south_row["total_revenue"], 49500.0), f"South total_revenue expected 49500.0, got {south_row['total_revenue']}")
    assert_test(south_row["store_count"] == 2, f"South store_count expected 2 (stores 103 and 104), got {south_row['store_count']}")

    # Test 4: Sorting descending by total_revenue
    assert_test(summary.iloc[0]["region"] == "West", "First row in region_summary should be 'West' (highest revenue)")

    return report
''',
    "hints": [
        "Use pd.concat(quarterly_dfs, ignore_index=True) to stack quarterly reports into one table.",
        "Use pd.merge(annual_sales, store_locations, on='store_id', how='left') to attach regional info.",
        "Use .groupby('region', as_index=False).agg(...) with total_revenue=('revenue', 'sum') and store_count=('store_id', 'nunique').",
        "Sort with .sort_values('total_revenue', ascending=False).reset_index(drop=True)."
    ]
}

CHALLENGES = [CHALLENGE_1, CHALLENGE_2]

CURRICULUM_DATA = {
    **DAY_METADATA,
    "concept_primer": CONCEPT_PRIMER,
    "walkthrough": WALKTHROUGH,
    "challenges": CHALLENGES,
}

def get_curriculum() -> Dict[str, Any]:
    return CURRICULUM_DATA
